---
- hosts: all
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.100 master.labk8s.corp.br
        - 192.168.99.101 master1.labk8s.corp.br
        - 192.168.99.102 master2.labk8s.corp.br
        - 192.168.99.103 node.labk8s.corp.br
        - 192.168.99.104 node1.labk8s.corp.br
        - 192.168.99.105 node2.labk8s.corp.br
        - 192.168.99.106 haproxy.labk8s.corp.br
    - name: Instalando pacotes de dependencias
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - unzip
        - python3
        - python3-pip
        - software-properties-common
        - vim
        - telnet
        - git
        - python-netaddr
        - snap
        - snapd
        - net-tools
        - haproxy
        update_cache: yes
    - name: Criando o arquivo de configuracao haproxy
      copy:
        src: files/haproxyconf.sh
        dest: /tmp
        mode: 0644
    - name: instala kubernets dependencias
      shell: sh haproxyconf.sh
      args:
        chdir: /tmp