---
- name: master
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: master.k8s.corp.br
  ipaddress: 192.168.99.100
  memory: 2048
  cpus: 2
  provision: provision/ansible/master.yaml

- name: node1
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: node1.k8s.corp.br
  ipaddress: 192.168.99.101
  memory: 2048
  cpus: 2
  provision: provision/ansible/nodes.yaml

- name: node2
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: node2.k8s.corp.br
  ipaddress: 192.168.99.102
  memory: 2048
  cpus: 2
  provision: provision/ansible/nodes.yaml
